### PR TITLE
dexpreopt the apex images

### PR DESCRIPTION
**Pull request by ghost**
Test: build

Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>

Just build and make sure build system says these:
"dexpreopt apex jars arm64"
"dexpreopt apex jars arm"

### CODE REVIEW

**Comment by thestinger** [comment]
Is it possible this is already done via https://android.googlesource.com/platform/build/+/refs/tags/android-10.0.0_r38/target/board/BoardConfigMainlineCommon.mk ?

Also this should probably be done for all devices if it isn't already.

**Comment by ghost** [comment]
Actually that's pretty weird because that flag actually does result in 2 extra compile steps for me

Maybe the issue is elsewhere

Closing this for now

**Comment by thestinger** [comment]
You might be correct that this is needed. I'm not sure if that file is included.

**Comment by thestinger** [comment]
Can you check what difference it makes in the output? And maybe try to figure out if that file is included and if it should be?

**Pull request closed without merging**
